apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.coordinator.name }}
  labels:
    {{- include "citus.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
spec:
  type: {{ .Values.coordinator.service.type }}
  ports:
    - port: {{ .Values.coordinator.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "citus.coordinatorSelectorLabels" . | nindent 4 }}
