{{- if .Values.init.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "citus.fullname" . }}-setup
  labels:
    {{- include "citus.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 5
  template:
    metadata:
      labels:
        {{- include "citus.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "citus.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
        - name: citus-setup
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/bash", "/scripts/setup-citus.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ include "citus.fullname" . }}-scripts
            defaultMode: 0755
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "citus.fullname" . }}-init-sample
  labels:
    {{- include "citus.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 5
  template:
    metadata:
      labels:
        {{- include "citus.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "citus.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
        - name: init-sample-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/bash", "/scripts/init-sample-db.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ include "citus.fullname" . }}-scripts
            defaultMode: 0755
{{- end }}
