apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.workers.name }}
  labels:
    {{- include "citus.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  serviceName: {{ .Values.workers.name }}
  replicas: {{ .Values.workers.replicas }}
  selector:
    matchLabels:
      {{- include "citus.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "citus.workerSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "citus.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            # Citus-specific environment variables
            - name: CITUS_NODE_ROLE
              value: "worker"
          ports:
            - name: postgres
              containerPort: {{ .Values.postgresql.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgresql.username }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgresql.username }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.workers.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  {{- if .Values.workers.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.workers.persistence.storageClass }}
        storageClassName: {{ .Values.workers.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.workers.persistence.size }}
  {{- end }}
