apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.workers.name }}
  labels:
    {{- include "citus.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: {{ .Values.workers.service.type }}
  ports:
    - port: {{ .Values.workers.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "citus.workerSelectorLabels" . | nindent 4 }}
  # This is a headless service needed for StatefulSet
  clusterIP: None
